site_name: 3D Printer Docs
site_url: https://3d-printer-docs.readthedocs.io/
theme:
  name: material
  features:
    - navigation.tabs

copyright: Devon Mar 2021
repo_url: https://github.com/devon-mar/3d-printer-docs
edit_uri: edit/master/docs
repo_name: GitHub

markdown_extensions:
  - admonition
  - pymdownx.tabbed
